version: 2

updates:

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "Jorich"
      - "pr11t"
      - "rammrain"
    groups:
      all-deps-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "Jorich"
      - "pr11t"
      - "rammrain"
