image: gradle:7.5.1-jdk11

clone:
  depth: full # SonarCloud scanner needs the full history to assign issues properly

definitions:

  caches:
    sonar: ~/.sonar/cache

  services:
    docker:
      memory: 2048

  steps:
    - step: &testLint
        name: Test and lint
        services:
          - docker
        caches:
          - gradle
          - docker
          - sonar
        script:
          - ./deploy/injectGradleCredentials.sh "$NEXUS_USERNAME" "$NEXUS_PASSWORD" "gradle.properties"
          - export TESTCONTAINERS_RYUK_DISABLED=true
          - gradle unitTest --fail-fast --no-daemon
          - gradle integrationTest --fail-fast --no-daemon
          - gradle jacocoUnitTestReport jacocoIntegrationTestReport --no-daemon
          - gradle copyDependencies sonarqube -x test --no-watch-fs
        artifacts:
          - build/reports/tests/**

    - step: &publishPreRelease
        name: Publish SNAPSHOT version
        caches:
          - gradle
        script:
          - ./deploy/injectGradleCredentials.sh "$NEXUS_USERNAME" "$NEXUS_PASSWORD" "gradle.properties"
          - ./deploy/setSnapshotVersion.sh
          - gradle build -x test
          - gradle publish

    - step: &publishRelease
        name: Publish release version
        trigger: manual
        caches:
          - gradle
        script:
          - ./deploy/injectGradleCredentials.sh "$NEXUS_USERNAME" "$NEXUS_PASSWORD" "gradle.properties"
          - gradle publish --no-daemon

pipelines:
  pull-requests:
    '**':
      - step: *testLint
      - step: *publishPreRelease
  branches:
    master:
      - step: *testLint
      - step: *publishPreRelease
      - step: *publishRelease
