name: Update Spring Versions Matrix

on:
  schedule:
    - cron: '0 3 1 * *'  # Monthly on the 1st at 03:00 UTC
  workflow_dispatch:      # Allow manual trigger as well

jobs:
  update-matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install packaging

      - name: Run update script
        run: python .github/scripts/update-spring-versions.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: update Spring Boot/Framework testing matrix"
          title: "Update Spring Versions Matrix"
          body: |
            This PR updates the `spring-versions.json` matrix with the latest patch versions of Spring Boot and their corresponding Spring Framework versions for Java 17 and 21.
          branch: update/spring-versions-matrix
          labels: |
            dependencies
            spring
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
